# AUTOGENERATED FILE - DO NOT EDIT

import pytest

import sys
import os
sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../..")
import uxid




def test_uxid_decode_exists():
    """
    UXID decode exists
    """
    result = uxid.decode("01E9VB3RWNAR89HSKMS84K9HCS")
    assert result, "Expected result to be defined"





def test_returns_a_uxid_with_input():
    """
    returns a UXID with input
    """
    input_string = "01E9VB3RWNAR89HSKMS84K9HCS"

    decoded_id = uxid.decode(input_string)
    assert isinstance(decoded_id, uxid.UXID)
    assert decoded_id.encoded == "01E9VB3RWNAR89HSKMS84K9HCS"



def test_rejects_blank_strings():
    """
    rejects blank strings
    """
    input_string = ""

    with pytest.raises(ValueError) as err:
      uxid.decode(input_string)
    assert "input is required" in str(err.value)



