// AUTOGENERATED FILE - DO NOT EDIT

import UXID from "../../src/uxid"


describe("0101 basic decoding: api", () => {

});


describe("0101 basic decoding: decoder", () => {

  test("accepts a ULID", () => {
    const input_string = "01E9VB3RWNAR89HSKMS84K9HCS";

    const uxid = UXID.decode(input_string);
    expect(uxid).toBeInstanceOf(UXID)

    expect(uxid.time).toBe(1591129269141);

  });

  test("accepts the maximum allowed timestamp", () => {
    const input_string = "7ZZZZZZZZZZZZZZZZZZZZZZZZZ";

    const uxid = UXID.decode(input_string);
    expect(uxid).toBeInstanceOf(UXID)

    expect(uxid.time).toBe(281474976710655);

  });

  test("rejects malformed strings", () => {
    const input_string = "this is not a UXID";

    expect(() => {
      UXID.decode(input_string);
    }).toThrow("expected input to be a Base32 encoded string, got: 'this is not a UXID'")

  });

});
