// AUTOGENERATED FILE - DO NOT EDIT
package uxid

import (
	"testing"
  "github.com/stretchr/testify/assert"
)


func Test_0001_API(t *testing.T) {
  t.Parallel()



  t.Run("UXID decode exists", func(t *testing.T) {
    got, err := Decode("01E9VB3RWNAR89HSKMS84K9HCS")
    assert.Nil(t, err)
    assert.NotNil(t, got)
  })

}



func Test_0001_Decoder(t *testing.T) {
  t.Parallel()


  t.Run("returns a UXID with input", func(t *testing.T) {
    inputString := "01E9VB3RWNAR89HSKMS84K9HCS"

    got, err := Decode(inputString)
    assert.Nil(t, err)
    // assert isinstance(decoded_id, uxid.UXID)
    if (assert.NotNil(t, got)) {
    assert.Equal(t, got.encoded, "01E9VB3RWNAR89HSKMS84K9HCS")

    }

  })

  t.Run("rejects blank strings", func(t *testing.T) {
    inputString := ""

    got, err := Decode(inputString)
    assert.Nil(t, got)
    assert.Error(t, err)

  })

}

