// AUTOGENERATED FILE - DO NOT EDIT
package uxid

import (
	"testing"
  "github.com/stretchr/testify/assert"
)


func Test_0101_API(t *testing.T) {
  t.Parallel()


}



func Test_0101_Decoder(t *testing.T) {
  t.Parallel()


  t.Run("accepts a ULID", func(t *testing.T) {
    inputString := "01E9VB3RWNAR89HSKMS84K9HCS"

    got, err := Decode(inputString)
    assert.Nil(t, err)
    // assert isinstance(decoded_id, uxid.UXID)
    if (assert.NotNil(t, got)) {

    assert.Equal(t, got.time, 1591129269141)
    }

  })

  t.Run("accepts the maximum allowed timestamp", func(t *testing.T) {
    inputString := "7ZZZZZZZZZZZZZZZZZZZZZZZZZ"

    got, err := Decode(inputString)
    assert.Nil(t, err)
    // assert isinstance(decoded_id, uxid.UXID)
    if (assert.NotNil(t, got)) {

    assert.Equal(t, got.time, 281474976710655)
    }

  })

  t.Run("rejects malformed strings", func(t *testing.T) {
    inputString := "this is not a UXID"

    got, err := Decode(inputString)
    assert.Nil(t, got)
    assert.Error(t, err)

  })

}

