root: true
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020,
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier/@typescript-eslint
  - plugin:prettier/recommended
env:
  node: true
  browser: true
  jest: true
